kind: pipeline
type: docker
name: default

clone:
  git:
    image: plugins/git
    recursive: true

steps:
- name: submodules
  image: alpine/git
  commands:
  - git submodule update --init --recursive

- name: build
  image: lagerdata/devenv-cortexm
  commands:
  - ln -s /drone/src /app
  - lager exec my_build_cmd

- name: flash
  image: lagerdata/devenv-cortexm

  commands:
  - lager connect --device nrf52 --interface ftdi --transport swd --speed 4000  --force --gateway 1
  - lager testrun --serial-device /dev/ttyACM0 --hexfile _build/unit-tests/test-suites/test-example/test-example.hex --test-runner unity --gateway 1
  - lager testrun --serial-device /dev/ttyACM0 --hexfile _build/unit-tests/test-suites/test-ledctrl/test-ledctrl.hex --test-runner unity --gateway 1
  - lager flash --hexfile _build/app/app.hex --gateway 1
  - lager run --gateway 1

trigger:
  branch:
  - master
