name: Simple pipeline to build firmware, flash DUT, and run tests
on: [push]
env:
  LAGER_GATEWAY: cuddly-cougar
  LAGER_WS_HOST: wss://f08bb0cc7a46.ngrok.io
  LAGER_HOST: https://f08bb0cc7a46.ngrok.io
  LAGER_CONFIG_FILE_NAME: .lager.dev
  LAGER_CLIENT_ID: XjJGqmcQdHo1DrpjmWdSFGJnfOrk2Asj 
  LAGER_AUDIENCE: https://dev.lagerdata.app/gateway 
  LAGER_AUTH_URL: https://dev-c-cvn8kq.auth0.com

jobs:
  build_flash_and_run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Build
        uses: docker://lagerdata/devenv-cortexm@sha256:2742d3fc1d3794d84afbe5aee79a1854a9079a2468d26d083f5d67c98435db3a
        with:
          entrypoint: /usr/local/bin/lager
          args: exec make

      - name: Connect to debugger
        uses: docker://lagerdata/lager-cli:v0.1.37
        env:
          LAGER_SECRET_TOKEN: ${{ secrets.DAVID_SECRET_TOKEN }}
        with:
          entrypoint: /usr/local/bin/lager
          args: connect --device nrf52 --force

      - name: wtf
        uses: docker://lagerdata/lager-cli:v0.1.37
        env:
          LAGER_SECRET_TOKEN: ${{ secrets.DAVID_SECRET_TOKEN }}
        with:
          entrypoint: /usr/bin/pwd

      - name: wtf2
        uses: docker://lagerdata/lager-cli:v0.1.37
        env:
          LAGER_SECRET_TOKEN: ${{ secrets.DAVID_SECRET_TOKEN }}
        with:
          entrypoint: /usr/bin/ls
          args: -alh


      - name: Flash and run
        uses: docker://lagerdata/lager-cli:v0.1.37
        env:
          LAGER_SECRET_TOKEN: ${{ secrets.DAVID_SECRET_TOKEN }}
        with:
          entrypoint: /usr/local/bin/lager
          args: testrun --serial-device /dev/ttyACM0 --hexfile _build/unit-tests/test-suites/test-ledctrl/test-ledctrl

